scan_filter_node:
  ros__parameters:
    scan_filter_chain:
      - name: arm_mask_left
        type: laser_filters/LaserScanAngularBoundsFilterInPlace
        params:
          lower_angle: 1.30   # Matches 9cm left, with padding
          upper_angle: 1.84   # Matches 9cm left, with padding
      - name: arm_mask_right
        type: laser_filters/LaserScanAngularBoundsFilterInPlace
        params:
          lower_angle: -1.84  # Matches 9cm right, with padding
          upper_angle: -1.30  # Matches 9cm right, with padding
