# Simple SLAM Toolbox Configuration for Testing
# Minimal config to get mapping working
slam_toolbox:
  ros__parameters:
    # General Parameters
    use_sim_time: false
    
    # ROS Parameters  
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    
    # Basic mapping parameters
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    
    # Stack size
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    
    # Scan matching - simplified
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    
    # Loop closure - disabled for now
    do_loop_closing: false
    
    # Solver parameters
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None