# Configuration for joy_linux and teleop_twist_joy with Logitech F710
# joy_linux configuration
joy_linux_node:
  ros__parameters:
    device_name: "/dev/input/js0"  # Default joystick device
    deadzone: 0.05
    autorepeat_rate: 20.0
    coalesce_interval_ms: 1
    default_trig_val: false

# teleop_twist_joy configuration  
teleop_twist_joy:
  ros__parameters:
    # Axis mappings for Logitech F710 controller
    # Left stick: axis 0 (horizontal), axis 1 (vertical)
    # Right stick: axis 3 (horizontal), axis 4 (vertical)
    axis_linear:
      x: 1        # Left stick vertical for forward/backward
    axis_angular:
      yaw: 0      # Left stick horizontal for turning
    
    # Velocity scaling - matches motor driver limits
    scale_linear:
      x: 0.5      # Maximum linear velocity (m/s)
    scale_angular:
      yaw: 0.2    # Maximum angular velocity (rad/s)

    # Button configuration for Logitech F710
    # A: 0, B: 1, X: 2, Y: 3
    # LB: 4, RB: 5  
    # Back: 6, Start: 7
    # Left stick: 9, Right stick: 10
    enable_button: 4      # Left bumper (LB) - must hold to enable movement
    # enable_turbo_button: 5  # Right bumper (RB) - turbo mode (DISABLED)
    
    # Turbo mode scaling (DISABLED)
    # scale_linear_turbo:
    #   x: 2.0      # 2x speed in turbo mode
    # scale_angular_turbo:
    #   yaw: 2.0    # 2x turning speed in turbo mode
    
    # Require enable button to be held for safety
    require_enable_button: true
    publish_stamped_twist: true  # Use StampedTwist messages
    
