uint32 qppr
uint32 max_speed
uint32 max_speed_qpps
uint32 accel
uint32 accel_qpps

int32  m1_qpps
float32   m1_speed
float32  m1_motor_current
uint32  m1_encoder_value
uint8  m1_encoder_status

int32  m2_qpps
float32   m2_speed
float32  m2_motor_current
uint32  m2_encoder_value
uint8  m2_encoder_status

float32  main_battery_voltage
float32  logic_battery_voltage
float32  temperature
string  error_string